module.exports = {
  ROLES: {
    ADMIN: "ADMIN",
    PARENT: "PARENT",
  },
  ORDER_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  DELIVERY_STATUS: {
    PENDING: "PENDING",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
  },
};
